_BASE_: "./Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "checkpoints/swin_tiny_patch4_window7_224_d2.pth"
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  ROI_BOX_HEAD:
    #    OUTPUT_LAYERS: "CosineFastRCNNOutputLayers" # baseline use a simple cosine FRCNN
    OUTPUT_LAYERS: "OpenDetFastRCNNOutputLayers_Soft"
  #    NORM: "SyncBN"
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2012_trainval')
  TEST: ('voc_2007_test', 'voc_coco_20_40_test', 'voc_coco_20_60_test', 'voc_coco_20_80_test', 'voc_coco_2500_test', 'voc_coco_5000_test', 'voc_coco_10000_test', 'voc_coco_20000_test')
SOLVER:
  STEPS: (21000, 29000)
  MAX_ITER: 32000
  IMS_PER_BATCH: 16
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.00003
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True

#CUDA_VISIBLE_DEVICES=4,5,6,7 python tools/train_net.py --num-gpus 4 --dist-url auto --config-file configs/faster_rcnn_Swin_T_FPN_3x_opendet.yaml OUTPUT_DIR "./output/faster_rcnn_Swin_T_FPN_3x_opendet_soft_b32_lr0005"
#CUDA_VISIBLE_DEVICES=0,1,2,3 python tools/train_net.py --num-gpus 4 --dist-url auto --config-file configs/faster_rcnn_Swin_T_FPN_3x_opendet.yaml OUTPUT_DIR "./output/faster_rcnn_Swin_T_FPN_3x_opendet_soft_b16_lr0003"